name: edgex-device-gpio
base: core22
license: Apache-2.0
summary: EdgeX GPIO Device Service
description: Refer to https://snapcraft.io/edgex-device-gpio
adopt-info: device-gpio
  
grade: stable
confinement: strict

# 0: kamakura, levski
# 1: minnesota
epoch: 1

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

slots:
  edgex-secretstore-token:
    interface: content
    source:
      write: [$SNAP_DATA/device-gpio]
      
plugs:
  device-gpio-config:
    interface: content
    target: $SNAP_DATA/config/device-gpio

apps:
  device-gpio:
    command: bin/device-gpio --configDir $SNAP_DATA/config/device-gpio/res --configProvider --registry
    command-chain:
      - bin/source-env-file.sh
    environment:
      DEVICE_PROFILESDIR: $SNAP_DATA/config/device-gpio/res/profiles
      DEVICE_DEVICESDIR: $SNAP_DATA/config/device-gpio/res/devices
      SECRETSTORE_TOKENFILE: $SNAP_DATA/device-gpio/secrets-token.json
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
      - gpio # not connected automatically

parts:
  helper-go:
    source: snap/local/helper-go
    plugin: make
    build-snaps: [ go/1.20/stable ]
    override-build: |
      cd $CRAFT_PART_SRC
      make build
      install -DT ./helper-go $CRAFT_PART_INSTALL/bin/helper-go
    
  device-gpio:
    source: .
    plugin: make
    build-packages: [git]
    build-snaps: [go/1.20/stable]
    override-build: |
      cd $CRAFT_PART_SRC

      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi
      
      # set the version of the snap
      craftctl set version=$VERSION
      
      # write version to file for the build
      echo $VERSION > VERSION

      make build
      
      install -DT cmd/device-gpio $CRAFT_PART_INSTALL/bin/device-gpio

      RES=$CRAFT_PART_INSTALL/config/device-gpio/res/
      mkdir -p $RES
      cp -r cmd/res/* $RES
      
      DOC=$CRAFT_PART_INSTALL/usr/share/doc/device-gpio
      mkdir -p $DOC
      cp Attribution.txt $DOC/Attribution.txt
      cp LICENSE $DOC/LICENSE
      
  local-bin:
    plugin: dump
    source: snap/local/bin
    organize:
      source-env-file.sh: bin/source-env-file.sh

